### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by PeterTheOne** [SemanticMediaWiki/SemanticComments#17]
- [ ] https://github.com/SemanticMediaWiki/SemanticComments/issues/1
- [ ] https://github.com/SemanticMediaWiki/SemanticComments/issues/5
- [ ] https://github.com/SemanticMediaWiki/SemanticComments/issues/16 ?
- [ ] Write Release Notes
- [ ] Update Installation Instructions
- [ ] Extend Readme
- [ ] ...

(Feel free to edit this text if something is missing)

**Comment by krabina** [comment]
prepared the language json files in PR #19

**Comment by krabina** [comment]
built some basic release notes and readme.

**Comment by kghbln** [comment]
Just wanted to drop a big cheer-up for making the release.

**Comment by mwjames** [comment]
> Just wanted to drop a big cheer-up for making the release.

Is there a way to make this repo a bit more like all the other repos  (PSR-4, namespace, directory structure, Travis-CI etc.) in SemanticMediaWiki so that maintenance becomes a bit more easier. 

How about making a 1.x release for the fixes already applied and make a "real" 2.0 where the repo becomes somewhat sane.

**Comment by kghbln** [comment]
> How about making a 1.x release for the fixes already applied and make a "real" 2.0 where the repo becomes somewhat sane.

Good idea.

**Comment by kghbln** [comment]
This extension was abandoned. See https://github.com/SemanticMediaWiki/SemanticComments/issues/25 for further details and an alternative.
