### ISSUE TITLE
Retire SemanticComments repository

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticComments#26]
As a result of the discussion on #25 this repository will be abandoned. Tasks to do:
- [x] Update README
- [x] Close open issue with reference to #25 
- [x] Close pull requests with reference to #25 
- [x] Update docu on MW.o
- [x] Update docu on S-MW.o
- [x] Update data on Wikidata
- [x] Mark repo as opsolete
- [x] Archive repo on GitHub via settings
